<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="description" content="">
		<meta name="author" content="">
		<link rel="icon" href="http://localhost/public/images/favicon.ico">


	    <!-- Custom styles for this template -->
	    <link rel="stylesheet" href="http://localhost/public/css/starter-template.css">
		<link rel="stylesheet" href="http://localhost/public/css/bootstrap.min.css">
		<link rel="stylesheet" href="http://localhost/public/css/bootstrap-theme.min.css">
	</head>
  	<body>
  		<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
			<div class="container">
				<div class="navbar-header">
		  			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
		  			</button>
		  			<a class="navbar-brand" href="#">Project name</a>
				</div>
				<div id="navbar" class="collapse navbar-collapse">
					<ul class="nav navbar-nav">
						<li class="active"><a href="#">Home</a></li>
						<li><a href="#about">About</a></li>
						<li><a href="#contact">Contact</a></li>
					</ul>
				</div><!--/.nav-collapse -->
			</div>
		</nav>

		<div class="container">
			<div class="starter-template">
				<h1>Bootstrap starter template</h1>
				<?php require $view->_content; ?>
			</div>
		</div>
		<script src="http://localhost/public/js/jquery.2.1.1.min.js"></script>
		<script src="http://localhost/public/js/restfulizer.js"></script>
		<script src="http://localhost/public/js/lib.js"></script><!-- Latest compiled and minified CSS -->
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
	</body>
</html>